spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: '{cipher}9df4e24da1dcb9cce6da9058c786fde57b3ee59002fdc828df2724e23f41e2f4'
    password:
    driver-class-name: org.h2.Driver

token:
  expiration_time: 777777
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==

gateway:
  ip: 192.168.0.8 

application:
  environment: develop 